format_version: 10
pipelines:
  test:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-de25e05:
        git: https://github.com/khgong/test.git
        username: ''
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - external:
                id: nginx
                store_id: khgong
                configuration:
                  options:
                    Image: test/nginx
                    Tag: latest
            tasks:
            - exec:
                arguments:
                - kubectl apply -f nginx.yaml -n gocd
                command: /bin/bash
                run_if: passed
