format_version: 10
pipelines:
  test:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-de25e05:
        git: https://github.com/khgong/test.git
        username: ''
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - clean
                - test
                command: mvn
                run_if: passed
